# Copyright (c) 2026 Mark Buckwell and contributors
# SPDX-License-Identifier: MIT

"""Bundles a git repository's own tracked (and untracked-but-not-ignored)
text/source files into a single PDF - one file per page, 8pt Courier,
wrapped lines, a running header (the report's own name on the left, that
page's own file path on the right), and a "Page N of M" footer.

This is deliberately independent of the rest of `prodockit.pdf`
(`build.py`/`html.py`/`css.py`/`lua.py`): there's no Markdown here, just
raw source text, so there's nothing for Pandoc's own HTML/Markdown
round-trip handling to do - this module builds one small, self-contained
HTML document directly and hands it straight to `weasyprint`, skipping
Pandoc entirely.
"""

from __future__ import annotations

import html
import os
import shutil
import subprocess
import tempfile


class SourceBundleError(RuntimeError):
    """Raised when the underlying `git` or `weasyprint` invocation fails.
    `returncode` and `stderr` (if captured) are attached for a caller that
    wants to inspect or log the failure, rather than just the formatted
    message."""

    def __init__(
        self, message: str, *, returncode: int | None = None, stderr: str | None = None
    ) -> None:
        super().__init__(message)
        self.returncode = returncode
        self.stderr = stderr


# Directory names always skipped when discovering source files, regardless
# of `.gitignore` or any project-level config - these hold vendored tooling
# assets a project ships with (e.g. a `custom_icons` directory, per
# pymdownx.emoji's own convention - see zensical.toml's
# `options.custom_icons`; or a Vale `StylesPath`, holding downloaded rule
# packs, per Vale's own conventional "styles" default), not content a
# student/author actually wrote. `.gitignore` alone can't solve this: these
# directories are typically *tracked* (committed, needed for the site/PDF
# to build at all), and `git ls-files --exclude-standard` only omits
# untracked-but-ignored paths, never already-tracked ones. Deliberately not
# a project-configurable setting, so a bundle's contents can't accidentally
# be narrowed by a project (or a student editing its config) reaching for
# the same knob to exclude something that actually should be archived.
#
# "styles" is a bare, generic name (unlike the dot-prefixed ".icons") and
# could in principle collide with a project's own directory of the same
# name - accepted deliberately, matching the same "not configurable" intent
# as ".icons": a project that hits this collision renames its own
# directory rather than gaining a knob to switch the exclusion off.
_EXCLUDED_DIR_NAMES = frozenset({".icons", "styles"})

# File *names* (not paths, and not directories) always skipped for the same
# reason as `_EXCLUDED_DIR_NAMES` above - dependency lockfiles are
# machine-generated by a package manager, never hand-written, and can run
# to thousands of lines each (a single `package-lock.json` can easily
# dwarf an entire bundle's worth of a student's actual source).
_EXCLUDED_FILE_NAMES = frozenset(
    {
        "package-lock.json",
        "npm-shrinkwrap.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "Pipfile.lock",
        "poetry.lock",
        "Cargo.lock",
    }
)


def _is_excluded(rel_path: str) -> bool:
    """True if `rel_path` (a `/`-separated, root-relative path, as `git
    ls-files` always reports regardless of OS) sits under a directory
    named in `_EXCLUDED_DIR_NAMES` - checked by directory *name* rather
    than a fixed path prefix, so it still matches regardless of which
    directory a project's own config points a tool at (e.g. both
    `overrides/.icons/...` and a top-level `.icons/...`) - or is itself
    named in `_EXCLUDED_FILE_NAMES`."""
    parts = rel_path.split("/")
    return (
        any(part in _EXCLUDED_DIR_NAMES for part in parts[:-1])
        or parts[-1] in _EXCLUDED_FILE_NAMES
    )


def discover_source_files(root: str = ".") -> list[str]:
    """Returns every file under `root` that `.gitignore` doesn't exclude,
    as `root`-relative paths sorted alphabetically - both already-tracked
    files and untracked-but-not-ignored ones (a brand new file nobody's
    run `git add` on yet still counts as "not excluded by .gitignore") -
    except for anything under an always-excluded directory, or named as
    an always-excluded file (see `_EXCLUDED_DIR_NAMES`/`_EXCLUDED_FILE_NAMES`),
    which is filtered out unconditionally.

    Shells out to `git ls-files --cached --others --exclude-standard`
    rather than reimplementing `.gitignore`'s own matching rules (nested
    `.gitignore` files, global excludes, negation patterns, and so on) -
    `git` already has to get every one of those exactly right, and `root`
    is a git working tree in every real use of this function (`prodockit
    pdf`'s own CLI only ever runs from a project's repository root).

    Raises `SourceBundleError` if `root` isn't a git working tree, or `git`
    itself isn't on `PATH`.
    """
    try:
        result = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
            cwd=root,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise SourceBundleError("git is not installed or not on PATH") from exc
    if result.returncode != 0:
        raise SourceBundleError(
            f"git ls-files failed in {root!r}",
            returncode=result.returncode,
            stderr=result.stderr,
        )
    all_files = sorted(line for line in result.stdout.splitlines() if line)
    return [f for f in all_files if not _is_excluded(f)]


def is_probably_text(path: str) -> bool:
    """Returns whether `path` looks like a text file worth bundling, by
    content rather than file extension - reads (at most) the first 8 KiB
    and rejects anything containing a null byte or that isn't valid UTF-8,
    the same rough heuristic tools like `git diff` use to tell text from
    binary. Content-based rather than an extension allowlist/denylist so
    a new file type never needs this function updating to recognise it.

    Returns `False` (rather than raising) for a path that can't be read
    at all (e.g. a broken symlink) - nothing to bundle either way. Only
    sniffs the first 8 KiB, so a file that's valid UTF-8 there but not
    further in (e.g. a stray invalid byte, or a multi-byte character
    split exactly at the boundary) can still pass this check -
    `build_source_bundle` itself handles that case when it reads the
    whole file, skipping it the same way rather than crashing the build.
    """
    try:
        with open(path, "rb") as f:
            chunk = f.read(8192)
    except OSError:
        return False
    if b"\x00" in chunk:
        return False
    try:
        chunk.decode("utf-8")
    except UnicodeDecodeError:
        return False
    return True


def _css_escape(text: str) -> str:
    """Minimal escaping for a value substituted into a CSS `content: "..."`
    string (as opposed to `html.escape`, for values substituted into HTML
    markup) - just enough for a plain site/report name (backslash and
    double-quote), not a general-purpose CSS string escaper."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


_CSS_TEMPLATE = """
@page {
    size: __PDF_PAGE_SIZE__;
    margin: 1.5cm;
    @top-left {
        content: "__REPORT_NAME__" !important;
        font-family: Courier !important;
        font-size: 8pt !important;
    }
    @top-right {
        content: string(current-file) !important;
        font-family: Courier !important;
        font-size: 8pt !important;
    }
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages) !important;
        font-family: Courier !important;
        font-size: 8pt !important;
    }
}
body {
    font-family: Courier !important;
    font-size: 8pt !important;
    margin: 0 !important;
}
/* string-set only takes effect on an element that actually generates a
   box - confirmed directly that display: none silently drops it instead,
   leaving @top-right permanently empty. Zero-size-and-clipped (rather
   than display: none) keeps the box (and so the string-set) while still
   taking up no visible space.

   break-before belongs here, not on the following <pre> - confirmed
   directly that putting it on <pre> instead let this marker (a real,
   if invisible, box) render on the *previous* file's own last page,
   right before the break - so that page's own running header showed
   the *next* file's name instead of the file whose content actually
   filled it. Keeping marker and break on the same element means the
   string-set and the page it takes effect on always agree. */
.file-marker {
    string-set: current-file content();
    break-before: page !important;
    font-size: 0 !important;
    line-height: 0 !important;
    height: 0 !important;
    margin: 0 !important;
    overflow: hidden !important;
}
.file-marker:first-of-type {
    break-before: avoid !important;
}
pre {
    white-space: pre-wrap !important;
    overflow-wrap: break-word !important;
    margin: 0 !important;
}
"""


def build_source_bundle(
    output_path: str = "source_bundle.pdf",
    *,
    root: str = ".",
    report_name: str = "",
    page_size: str = "A4",
    work_dir: str | None = None,
    keep_work_dir: bool = False,
) -> int:
    """Builds a single PDF bundling every text file `.gitignore` doesn't
    exclude under `root` (see `discover_source_files`) and writes it to
    `output_path` (relative paths resolve against `root`, matching "the
    top-level directory" a project's own `root` already is). Returns how
    many files were actually included (binary files - see
    `is_probably_text` - and a file that turns out not to be valid UTF-8
    once fully read are both silently skipped, not counted as a failure).

    Each file starts on its own page, in 8pt Courier with wrapped lines
    (a `white-space: pre-wrap` for genuinely long lines, not `pre`'s own
    unwrapped default), a running header with `report_name` on the left
    and that page's own file path on the right, and a "Page N of M"
    footer - see this module's own `_CSS_TEMPLATE` for the exact rules.

    Raises `SourceBundleError` if the underlying `git`/`weasyprint`
    invocation fails (both `git` and a WeasyPrint install are required on
    `PATH` - this function doesn't install either).

    `work_dir`/`keep_work_dir` mirror `prodockit.pdf.build.build_pdf`'s
    own pair - `weasyprint` needs the concatenated HTML on disk somewhere;
    written under `work_dir` if given, or a fresh temporary directory
    otherwise, left in place afterwards only if `keep_work_dir` is set
    (only meaningful with an explicit `work_dir` - a temporary directory
    is always cleaned up regardless).
    """
    resolved_output_path = (
        output_path if os.path.isabs(output_path) else os.path.join(root, output_path)
    )

    files = discover_source_files(root)
    text_files = [f for f in files if is_probably_text(os.path.join(root, f))]

    use_temp_dir = work_dir is None
    resolved_work_dir: str = (
        tempfile.mkdtemp(prefix="prodockit-source-bundle-") if work_dir is None else work_dir
    )
    os.makedirs(resolved_work_dir, exist_ok=True)

    try:
        css = _CSS_TEMPLATE.replace("__PDF_PAGE_SIZE__", page_size).replace(
            "__REPORT_NAME__", _css_escape(report_name)
        )

        body_parts: list[str] = []
        for rel_path in text_files:
            try:
                with open(os.path.join(root, rel_path), encoding="utf-8") as f:
                    content = f.read()
            except (OSError, UnicodeDecodeError):
                # is_probably_text() only sniffs the first 8 KiB - a file
                # that's invalid UTF-8 beyond that (or vanished/became
                # unreadable since discover_source_files() ran) is skipped
                # here the same way a binary file already is, rather than
                # crashing the whole bundle.
                continue
            body_parts.append(
                f'<div class="file-marker">{html.escape(rel_path)}</div>'
                f"<pre>{html.escape(content)}</pre>"
            )

        html_path = os.path.join(resolved_work_dir, "_prodockit_source_bundle.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write("<!DOCTYPE html><html><head><meta charset=\"utf-8\">")
            f.write(f"<style>{css}</style>")
            f.write("</head><body>")
            f.write("\n".join(body_parts))
            f.write("</body></html>")

        cmd = ["weasyprint", html_path, resolved_output_path]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise SourceBundleError(
                f"weasyprint exited with status {result.returncode} "
                f"building {resolved_output_path!r}",
                returncode=result.returncode,
                stderr=result.stderr,
            )
        return len(body_parts)
    finally:
        if use_temp_dir or not keep_work_dir:
            shutil.rmtree(resolved_work_dir, ignore_errors=True)
