# Copyright (c) 2026 Mark Buckwell and contributors
# SPDX-License-Identifier: MIT

"""Generates the Pandoc Lua filter a PDF build needs alongside
:mod:`zendoc.pdf.html`'s HTML fixups.

Some of Zensical/pymdownx's own rendered output only becomes fully correct
for a PDF once Pandoc has parsed it into its own AST - not something
:mod:`zendoc.pdf.html`'s pre-parse HTML fixups can reach:

- Chapter-number/appendix-letter prefixing on every heading (``Header``),
  carried over onto figure/table caption numbers too (``Figure``, and the
  ``Div`` case for a prepend-position caption already retagged to a
  ``<div>`` by :mod:`zendoc.pdf.html`).
- Reconstructing ``pymdownx.blocks.tab``'s tabbed-set HTML (each tab's
  label rewritten to its own ``<p>`` by :mod:`zendoc.pdf.html`, since
  Pandoc's HTML reader would otherwise merge adjacent inline labels into
  one unseparated run of text) into one ``tabbox-header``/``tabbox-body``
  pair per tab (``Div``).
- Pre-rendering TeX math to static SVGs, since WeasyPrint has no JS engine
  to run MathJax client-side (``Math``, and the ``Div``/``Span`` cases for
  ``pymdownx.arithmatex``'s *generic*-mode math, which has no native Math
  AST node in Pandoc's *HTML* reader the way ``$...$``/``$$...$$`` does in
  its *markdown* reader).
- Inserting the generated Table of Contents at its own heading
  (``Pandoc``).
"""

from __future__ import annotations


def build_lua_filter(
    heading_numbering_enabled: bool,
    mathjax_available: bool,
    math_dir: str,
    tex2svg_script: str,
) -> str:
    """Returns the complete Lua filter source for a PDF build.

    `math_dir` is where a pre-rendered formula's SVG is written (must
    already exist or be creatable by the caller); `tex2svg_script` is the
    path to a Node script that renders one TeX formula to SVG on stdin/argv
    (see zendoc-template's own ``tools/mathjax/tex2svg.js`` for the
    expected CLI shape: ``node tex2svg.js <display|inline>``, formula on
    stdin, SVG on stdout). Both are ignored (no formula is rendered) when
    `mathjax_available` is False - e.g. no local MathJax install.
    """
    heading_numbering_lua = "true" if heading_numbering_enabled else "false"
    mathjax_available_lua = "true" if mathjax_available else "false"
    return (
        "local h1, h2, h3 = 0, 0, 0\n"
        "local appendix_index = 0\n"
        "local in_appendix = false\n"
        f"local heading_numbering_enabled = {heading_numbering_lua}\n\n"
        "-- Converts 1, 2, 3... to A, B, C... for appendix numbering. Single\n"
        "-- letters only - unlike CSS's own upper-alpha counter style, Lua has\n"
        "-- no built-in equivalent, and a report is never realistically going\n"
        "-- to have more than 26 appendixes.\n"
        "local function to_letter(n)\n"
        "  return string.char(64 + n)\n"
        "end\n\n"
        f"local mathjax_available = {mathjax_available_lua}\n"
        f"local math_dir = \"{math_dir}\"\n"
        f"local tex2svg_script = \"{tex2svg_script}\"\n"
        "local math_counter = 0\n\n"
        "function Div(el)\n"
        "  if el.classes:includes('tabbox') then\n"
        "    local title = el.attributes['title'] or 'Tab'\n"
        "    local header = pandoc.Div({pandoc.Plain({pandoc.Str(title)})}, {class='tabbox-header'})\n"
        "    local body = pandoc.Div(el.content, {class='tabbox-body'})\n"
        "    el.content = {header, body}\n"
        "    el.classes = {'tabbox-container'}\n"
        "    return el\n"
        "  end\n"
        "  -- Reconstructs pymdownx.blocks.tab's HTML structure into the same\n"
        "  -- tabbox-header/tabbox-body/tabbox-container shape as the .tabbox\n"
        "  -- case above, so both conventions share one CSS treatment. A\n"
        "  -- tabbed-set groups every tab's label (tabbed-labels, one block per\n"
        "  -- label) and content (tabbed-content, one tabbed-block Div per tab)\n"
        "  -- together, unlike the .tabbox case above (already split into one\n"
        "  -- Div per tab before Pandoc ever sees it) - walk both pairwise and\n"
        "  -- emit one tabbox-container per tab.\n"
        "  if el.classes:includes('tabbed-set') then\n"
        "    local labels_div, content_div\n"
        "    for _, child in ipairs(el.content) do\n"
        "      if child.t == 'Div' and child.classes:includes('tabbed-labels') then\n"
        "        labels_div = child\n"
        "      elseif child.t == 'Div' and child.classes:includes('tabbed-content') then\n"
        "        content_div = child\n"
        "      end\n"
        "    end\n"
        "    if not labels_div or not content_div then return el end\n"
        "    local tabs = {}\n"
        "    for i, label_block in ipairs(labels_div.content) do\n"
        "      local body_block = content_div.content[i]\n"
        "      if body_block then\n"
        "        local header = pandoc.Div({pandoc.Plain(label_block.content)}, {class='tabbox-header'})\n"
        "        local body = pandoc.Div(body_block.content, {class='tabbox-body'})\n"
        "        table.insert(tabs, pandoc.Div({header, body}, {class='tabbox-container'}))\n"
        "      end\n"
        "    end\n"
        "    return tabs\n"
        "  end\n"
        "  -- Prepend-position figure-caption/table-caption: pymdownx.blocks.\n"
        "  -- caption's own HTML places a prepended figcaption physically first\n"
        "  -- in the DOM, but Pandoc's Figure AST node stores Caption and\n"
        "  -- content as two separate fields regardless of original order, and\n"
        "  -- Pandoc's own HTML writer always re-emits the caption *after* the\n"
        "  -- content when serializing Figure back to HTML - discarding the\n"
        "  -- \"prepend\" positioning entirely (confirmed directly, isolated\n"
        "  -- test). zendoc.pdf.html works around this by retagging any\n"
        "  -- prepend-position figure/table caption to a <div> before Pandoc\n"
        "  -- parses it (a Div's children ARE emitted in original document\n"
        "  -- order), leaving the caption as this Div's first child block -\n"
        "  -- same \"Figure \"/\"Table \" + chapter-prefix numbering as the\n"
        "  -- Figure() handler below, applied to el.content[1] instead of\n"
        "  -- el.caption.long[1].\n"
        "  if el.classes:includes('zendoc-figure-caption') or el.classes:includes('zendoc-table-caption') then\n"
        "    local word = el.classes:includes('zendoc-figure-caption') and 'Figure ' or 'Table '\n"
        "    local label = in_appendix and to_letter(appendix_index) or tostring(h1)\n"
        "    local block = el.content[1]\n"
        "    if block and (block.t == 'Para' or block.t == 'Plain') then\n"
        "      for i, inline in ipairs(block.content) do\n"
        "        if inline.t == 'Span' and inline.classes:includes('caption-prefix') then\n"
        "          table.insert(inline.content, 1, pandoc.Str(label .. '.'))\n"
        "          table.insert(block.content, i, pandoc.Str(word))\n"
        "          break\n"
        "        end\n"
        "      end\n"
        "    end\n"
        "    return el\n"
        "  end\n"
        "  -- pymdownx.arithmatex's generic-mode display math\n"
        "  -- (<div class=\"arithmatex\">\\[...\\]</div>): Pandoc's HTML reader\n"
        "  -- has no native Math AST node for this the way its *markdown*\n"
        "  -- reader does for $$...$$, so this can't be handled by the Math()\n"
        "  -- function below at all - matched by class instead, stripping the\n"
        "  -- \\[ \\] delimiters before the same tex2svg render Math() uses.\n"
        "  if el.classes:includes('arithmatex') then\n"
        "    if not mathjax_available then return nil end\n"
        "    local text = pandoc.utils.stringify(el.content):gsub('^%s*\\\\%[%s*', ''):gsub('%s*\\\\%]%s*$', '')\n"
        "    math_counter = math_counter + 1\n"
        "    local ok, svg = pcall(pandoc.pipe, 'node', {tex2svg_script, 'display'}, text)\n"
        "    if not ok or not svg or svg == '' then return nil end\n"
        "    local svg_path = math_dir .. '/formula_' .. math_counter .. '.svg'\n"
        "    local out = io.open(svg_path, 'w')\n"
        "    if not out then return nil end\n"
        "    out:write(svg)\n"
        "    out:close()\n"
        "    return pandoc.Para({pandoc.RawInline('html', '<img class=\"pdf-math-display\" src=\"' .. svg_path .. '\" />')})\n"
        "  end\n"
        "end\n\n"
        "-- pymdownx.arithmatex's generic-mode inline math\n"
        "-- (<span class=\"arithmatex\">\\(...\\)</span>) - same reasoning as\n"
        "-- the Div() arithmatex handler above, for the inline case.\n"
        "function Span(el)\n"
        "  if el.classes:includes('arithmatex') then\n"
        "    if not mathjax_available then return nil end\n"
        "    local text = pandoc.utils.stringify(el.content):gsub('^%s*\\\\%(%s*', ''):gsub('%s*\\\\%)%s*$', '')\n"
        "    math_counter = math_counter + 1\n"
        "    local ok, svg = pcall(pandoc.pipe, 'node', {tex2svg_script, 'inline'}, text)\n"
        "    if not ok or not svg or svg == '' then return nil end\n"
        "    local svg_path = math_dir .. '/formula_' .. math_counter .. '.svg'\n"
        "    local out = io.open(svg_path, 'w')\n"
        "    if not out then return nil end\n"
        "    out:write(svg)\n"
        "    out:close()\n"
        "    return pandoc.RawInline('html', '<img class=\"pdf-math-inline\" src=\"' .. svg_path .. '\" />')\n"
        "  end\n"
        "end\n\n"
        "-- Prepends the current chapter number/appendix letter in front of\n"
        "-- pymdownx.blocks.caption's own bare per-page auto-number\n"
        "-- (e.g. \"1.\" -> \"7.1.\"), plus the \"Figure \"/\"Table \" word itself\n"
        "-- (added via CSS ::before on the website, which has no equivalent\n"
        "-- for a PDF, where the number needs to be real text) - matching\n"
        "-- zensical.toml's zendoc-figure-caption/zendoc-table-caption classes\n"
        "-- (see [project.markdown_extensions.pymdownx.blocks.caption]).\n"
        "function Figure(el)\n"
        "  local word = nil\n"
        "  if el.classes:includes('zendoc-figure-caption') then word = 'Figure '\n"
        "  elseif el.classes:includes('zendoc-table-caption') then word = 'Table ' end\n"
        "  if not word then return el end\n"
        "  local label = in_appendix and to_letter(appendix_index) or tostring(h1)\n"
        "  for _, block in ipairs(el.caption.long) do\n"
        "    if block.t == 'Para' or block.t == 'Plain' then\n"
        "      for i, inline in ipairs(block.content) do\n"
        "        if inline.t == 'Span' and inline.classes:includes('caption-prefix') then\n"
        "          table.insert(inline.content, 1, pandoc.Str(label .. '.'))\n"
        "          table.insert(block.content, i, pandoc.Str(word))\n"
        "          return el\n"
        "        end\n"
        "      end\n"
        "      return el\n"
        "    end\n"
        "  end\n"
        "  return el\n"
        "end\n\n"
        "function Header(block)\n"
        "  if heading_numbering_enabled and not block.classes:includes('unnumbered') then\n"
        "    if block.level == 1 then\n"
        "      h2 = 0\n"
        "      h3 = 0\n"
        "      if block.classes:includes('appendix') then\n"
        "        appendix_index = appendix_index + 1\n"
        "        in_appendix = true\n"
        "        table.insert(block.content, 1, pandoc.Str('Appendix ' .. to_letter(appendix_index) .. '. '))\n"
        "      else\n"
        "        h1 = h1 + 1\n"
        "        in_appendix = false\n"
        "        table.insert(block.content, 1, pandoc.Str(tostring(h1) .. '. '))\n"
        "      end\n"
        "    elseif block.level == 2 then\n"
        "      h2 = h2 + 1\n"
        "      h3 = 0\n"
        "      if in_appendix then\n"
        "        table.insert(block.content, 1, pandoc.Str(to_letter(appendix_index) .. '.' .. tostring(h2) .. ' '))\n"
        "      else\n"
        "        table.insert(block.content, 1, pandoc.Str(tostring(h1) .. '.' .. tostring(h2) .. ' '))\n"
        "      end\n"
        "    elseif block.level == 3 then\n"
        "      h3 = h3 + 1\n"
        "      if in_appendix then\n"
        "        table.insert(block.content, 1, pandoc.Str(to_letter(appendix_index) .. '.' .. tostring(h2) .. '.' .. tostring(h3) .. ' '))\n"
        "      else\n"
        "        table.insert(block.content, 1, pandoc.Str(tostring(h1) .. '.' .. tostring(h2) .. '.' .. tostring(h3) .. ' '))\n"
        "      end\n"
        "    end\n"
        "  end\n"
        "  return block\n"
        "end\n\n"
        "function Math(el)\n"
        "  if not mathjax_available then return nil end\n"
        "  math_counter = math_counter + 1\n"
        "  local is_display = (el.mathtype == 'DisplayMath')\n"
        "  local ok, svg = pcall(pandoc.pipe, 'node', {tex2svg_script, is_display and 'display' or 'inline'}, el.text)\n"
        "  if not ok or not svg or svg == '' then return nil end\n"
        "  local svg_path = math_dir .. '/formula_' .. math_counter .. '.svg'\n"
        "  local out = io.open(svg_path, 'w')\n"
        "  if not out then return nil end\n"
        "  out:write(svg)\n"
        "  out:close()\n"
        "  local css_class = is_display and 'pdf-math-display' or 'pdf-math-inline'\n"
        "  return pandoc.RawInline('html', '<img class=\"' .. css_class .. '\" src=\"' .. svg_path .. '\" />')\n"
        "end\n\n"
        "function Pandoc(doc)\n"
        "  local toc_list = pandoc.structure.table_of_contents(doc)\n"
        "  local final_blocks = {}\n"
        "  for _, block in ipairs(doc.blocks) do\n"
        "    table.insert(final_blocks, block)\n"
        "    if block.t == 'Header' and block.level == 1 and pandoc.utils.stringify(block.content) == 'Table of Contents' then\n"
        "      table.insert(final_blocks, pandoc.Div(toc_list, {id='TOC', class='toc'}))\n"
        "    end\n"
        "  end\n"
        "  doc.blocks = final_blocks\n"
        "  return doc\n"
        "end\n"
    )
