# Copyright (c) 2026 Mark Buckwell and contributors
# SPDX-License-Identifier: MIT

name: Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: sudo apt-get update && sudo apt-get install -y pandoc fonts-inter fonts-jetbrains-mono
      - run: pip install -e . weasyprint
      - run: prodockit pdf
      - run: prodockit pdf -m installation.md
      - run: prodockit pdf -m extensions/headings.md
      - run: prodockit pdf -m extensions/refs.md
      - run: prodockit pdf -m extensions/citations.md
      - run: prodockit pdf -m extensions/glossary.md
      - run: prodockit pdf -m extensions/tables.md
      - run: prodockit pdf -m extensions/bibliography.md
      - run: prodockit pdf -m pdf.md
      - run: prodockit pdf -m macros.md
      - run: prodockit pdf -m about/changelog.md
      - run: prodockit pdf -m about/license.md
      - run: zensical build --clean --strict
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
